M48
; DRILL file {KiCad (6.0.6-0)} date 2023 January 17, Tuesday 17:25:36
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2023-01-17T17:25:36+00:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.6-0)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C2.200
%
G90
G05
T1
X102.5Y-87.5
X102.5Y-117.5
X132.5Y-87.5
X132.5Y-117.5
T0
M30
